controller_manager:
  ros__parameters:
    update_rate: 50
    use_sim_time: true

    steering_wheel_left_controller:
      type: velocity_controllers/JointGroupVelocityController
    steering_wheel_right_controller:
      type: velocity_controllers/JointGroupVelocityController
    linear_actuator_controller:
      type: effort_controllers/JointGroupEffortController

      
steering_wheel_left_controller:
  ros__parameters:
    joints:
      - steering_wheel_left_joint
#    interface_name: velocity
    command_interfaces:
      - velocity
    state_interfaces:
      - position
      - velocity
#
#    state_publish_rate: 50.0
#    action_monitor_rate: 20.0
steering_wheel_right_controller:
  ros__parameters:
    joints:
      - steering_wheel_right_joint
#    interface_name: velocity
    command_interfaces:
      - velocity
    state_interfaces:
      - position
      - velocity
#
#    state_publish_rate: 50.0
#    action_monitor_rate: 20.0
linear_actuator_controller:
  ros__parameters:
    joints:
      - linear_actuator_joint
#    interface_name: effort
    command_interfaces:
      - effort
    state_interfaces:
      - position
      - velocity
#
#    state_publish_rate: 50.0
#    action_monitor_rate: 20.0